"""Versioned, curated task metadata. Submitted code is never executed."""
TASKS = [
    {"id": "AUTH-101", "title": "Refresh token race condition", "language": "Python", "category": "Authentication", "difficulty": "Hard", "description": "Concurrent refresh requests rotate the same token. Design an atomic rotation flow without weakening replay detection.", "context": "Two requests read the same active token before either commits. One succeeds, the other signs the user out. A stolen token must still be rejected.", "checks": ["Atomic token-family transition", "Bounded concurrent refresh handling", "Replay detection remains enabled", "Parallel refresh test plan", "Revocation regression test plan"]},
    {"id": "API-203", "title": "Idempotent order endpoint", "language": "TypeScript", "category": "API Design", "difficulty": "Medium", "description": "A timed-out POST is retried and creates duplicate orders. Specify an idempotent write contract.", "context": "Clients send an Idempotency-Key. Two workers may process the same key at once. A key reused with a different payload must be rejected.", "checks": ["Atomic unique key reservation", "Replay returns original result", "Tenant-scoped idempotency keys", "Conflicting payload test plan", "Concurrent duplicate regression plan"]},
    {"id": "DB-307", "title": "Slow tenant dashboard", "language": "SQL", "category": "Performance", "difficulty": "Hard", "description": "A tenant-filtered query sorts a growing events table. Propose and verify an index without crossing tenant boundaries.", "context": "The query filters tenant_id and orders by created_at DESC with a bounded limit. EXPLAIN shows a sequential scan. No measured improvement is supplied.", "checks": ["Index matches filter and sort", "Query plan verification", "Tenant isolation preserved", "Representative dataset test plan", "Write-cost regression plan"]},
    {"id": "SEC-411", "title": "Broken object authorization", "language": "Java", "category": "Security", "difficulty": "Hard", "description": "A record endpoint looks up a client-supplied ID without tenant scoping. Design an authorization-safe fix.", "context": "The authenticated identity contains tenantId. IDs are guessable. The fix must preserve authorized access and avoid revealing other tenants' record existence.", "checks": ["Scope lookup to authenticated tenant", "Consistent denial response", "Reject cross-tenant access", "Ownership boundary test plan", "Authorized access regression plan"]},
    {"id": "UI-118", "title": "Duplicate fetch loop", "language": "TypeScript", "category": "Frontend", "difficulty": "Medium", "description": "A React effect depends on results that it updates. Repair the dependency loop and stale responses.", "context": "Rapid query changes leave multiple requests in flight. A slower earlier response may overwrite the latest results. Component unmount must release resources.", "checks": ["Stable effect dependencies", "Cancel or ignore stale responses", "Safe query encoding", "Reordered response test plan", "Unmount cleanup regression plan"]},
    {"id": "OPS-502", "title": "Container health failure", "language": "Python", "category": "DevOps", "difficulty": "Medium", "description": "A release fails its readiness probe after configuration changes. Define a safe rollout and recovery plan.", "context": "The new revision is missing required configuration. The previous revision is healthy. Liveness should not depend on a third-party provider.", "checks": ["Validate configuration at startup", "Separate readiness and liveness", "Keep secrets out of logs", "Missing configuration test plan", "Rollback verification plan"]},
]

STARTER_CODE = {
    "AUTH-101": "token = db.find_refresh_token(raw_token)\nif token.active:\n    db.revoke(token.id)\n    return db.create_refresh_token(token.user_id)",
    "API-203": "app.post('/orders', async (req, res) => {\n  const order = await db.orders.create(req.body);\n  res.status(201).json(order);\n});",
    "DB-307": "SELECT id, created_at FROM events\nWHERE tenant_id = :tenant_id\nORDER BY created_at DESC LIMIT 50;\n-- Existing index: primary key(id) only",
    "SEC-411": "Record record = records.findById(request.id());\nif (record == null) return notFound();\nreturn ok(record); // identity.tenantId() is available",
    "UI-118": "useEffect(() => {\n  fetch(`/api/search?q=${query}`)\n    .then(r => r.json()).then(setResults);\n}, [query, results]);",
    "OPS-502": "provider_key = os.getenv('PROVIDER_KEY')\n@app.get('/health')\ndef health():\n    return provider.request_status(provider_key)",
}

def public_tasks():
    return [{**t, "starter_code": STARTER_CODE[t["id"]], "rubric_version": "1.1", "checks": [{"id": f"c{n}", "label": label} for n, label in enumerate(t["checks"])]} for t in TASKS]
